import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { formatOrderSide, formatOrderType } from './Trading';
import './Trading.css';

const OPEN_STATUSES = new Set(['OPEN', 'NEW', 'WORKING', 'PENDING', 'PARTIALLY_FILLED', 'PARTIALLY FILLED']);
const isWebull = (order) => String(order?.source || order?.origin || '').toLowerCase() === 'webull';
const amount = (value, digits = 6) => Number.isFinite(Number(value)) ? Number(value).toLocaleString(undefined, { maximumFractionDigits: digits }) : '—';
const timestamp = (value) => { const date = new Date(value); return value && !Number.isNaN(date.getTime()) ? date.toLocaleString() : '—'; };
const normalize = (order, source) => ({ ...order, source, id: order.id || order.order_id || order.orderId || `${source}-${order.symbol}-${order.created_at || order.create_time || Math.random()}`, symbol: String(order.symbol || order.ticker || '—').toUpperCase(), order_type: order.order_type || order.type || '—', quantity: order.quantity ?? order.total_quantity ?? order.order_quantity, filled_quantity: order.filled_quantity ?? order.executed_quantity ?? order.filled_qty, price: order.price ?? order.limit_price ?? order.order_price, status: order.status || order.order_status || '—', created_at: order.created_at || order.create_time || order.placed_time || order.time });

function SourceBadge({ order }) { const webull = isWebull(order); return <span className="badge" style={{ background: webull ? 'rgba(96, 165, 250, .16)' : 'rgba(251, 191, 36, .16)', color: webull ? '#60a5fa' : '#fbbf24' }}>{webull ? 'Webull · Read-only' : 'Binance.US'}</span>; }
function OrderTable({ orders, open }) { if (!orders.length) return <div className="empty-state"><p>No {open ? 'open' : 'historical'} orders for the selected accounts.</p></div>; return <div className="table-container trading-table"><div className="order-table-scroll"><table><thead><tr><th>Date / Time</th><th>Account</th><th>Symbol</th><th>Side</th><th>Type</th><th>Quantity</th><th>Price</th><th>Filled</th><th>Status</th>{open && <th>Actions</th>}</tr></thead><tbody>{orders.map((order) => <tr key={`${order.source}-${order.id}`}><td>{timestamp(order.created_at)}</td><td><SourceBadge order={order} /></td><td>{order.symbol}</td><td>{formatOrderSide(order.side)}</td><td>{formatOrderType(order.order_type)}</td><td>{amount(order.quantity)}</td><td>{Number(order.price) > 0 ? `$${amount(order.price, 4)}` : 'Market'}</td><td>{amount(order.filled_quantity)}</td><td>{order.status}</td>{open && <td>{isWebull(order) ? <span style={{ color: '#94a3b8' }}>Manage in Webull</span> : <span style={{ color: '#94a3b8' }}>Manage in Binance.US</span>}</td>}</tr>)}</tbody></table></div></div>; }

export default function Orders() {
  const [activeTab, setActiveTab] = useState('open'); const [history, setHistory] = useState([]); const [openOrders, setOpenOrders] = useState([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setNotice(''); try { const [historyResponse, binanceOpenResponse, webullOpenResponse] = await Promise.all([axios.get('/api/trading/real-orders?limit=all', { withCredentials: true }), axios.get('/api/pending-orders', { withCredentials: true }), axios.get('/api/webull/open-orders', { withCredentials: true })]); const allHistory = (historyResponse.data?.orders || []).map((order) => normalize(order, isWebull(order) ? 'webull' : 'binance')); setHistory(allHistory); const binance = (binanceOpenResponse.data?.pending_orders || []).map((order) => normalize(order, 'binance')); const webull = (webullOpenResponse.data?.orders || []).map((order) => normalize(order, 'webull')); setOpenOrders([...binance, ...webull]); if (webullOpenResponse.data?.success === false) setNotice(webullOpenResponse.data?.message || 'Webull open orders could not be refreshed.'); } catch (error) { setNotice(error.response?.data?.message || 'Unable to load combined orders.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); const activeOpenOrders = useMemo(() => openOrders.filter((order) => OPEN_STATUSES.has(String(order.status).toUpperCase()) || isWebull(order)), [openOrders]);
  return <div className="trading-page" style={{ padding: '20px', maxWidth: '1500px', margin: '0 auto' }}><div className="trading-header" style={{ marginBottom: 18 }}><div><h1 style={{ fontSize: '2rem', margin: 0 }}>📋 Orders</h1><p style={{ margin: '6px 0 0', color: '#94a3b8' }}>Open orders and history across Binance.US and Webull. Webull orders are read-only.</p></div><button type="button" className="btn btn-secondary" onClick={load}>🔄 Refresh</button></div>{notice && <div className="modern-real-warning" style={{ marginBottom: 16 }}>⚠️ {notice}</div>}<div className="trading-tabs"><button className={`tab-button ${activeTab === 'open' ? 'active' : ''}`} onClick={() => setActiveTab('open')}>⏳ <span className="tab-text">Open Orders</span>{activeOpenOrders.length > 0 && <span className="tab-badge">{activeOpenOrders.length}</span>}</button><button className={`tab-button ${activeTab === 'history' ? 'active' : ''}`} onClick={() => setActiveTab('history')}>📜 <span className="tab-text">Order History</span></button></div><div className="trading-content"><section className="order-history-container">{loading ? <div className="empty-state"><p>Loading combined orders…</p></div> : activeTab === 'open' ? <><h2>All Open Orders</h2><OrderTable orders={activeOpenOrders} open /></> : <><h2>All Order History</h2><OrderTable orders={history} /></>}</section></div></div>;
}
